### ISSUE TITLE
Modificación de Componente de Presentacion de la Ficha Residencial para incluir campos adicionales  a solicitud del DEPRODE - Residencias

### ISSUE THREAD

**Issue by julioparra1518** [ivansaldivar/proyectoFichaResidencial#23]

**Comment by ivansaldivar** [comment]
Agregué las modificaciones correspondientes a la componente de negocio de presentación (métodos WEB de microservicios) para la ficha residencial. 
Incorporé los nuevos parámetros a aquellos métodos que se asocian a los cambios de secciones que presentan nuevos campos (métodos que graban parcial y totalmente la ficha).
